services:
  postgres:
    image: postgres:16
    container_name: postgres-learning

    environment:
      POSTGRES_DB: analysis_db_prueba
      POSTGRES_USER: yailauc
      POSTGRES_PASSWORD: yailauc123

    ports:
      - "5434:5432"

    volumes:
      - analysis_postgres_data:/var/lib/postgresql/data

volumes:
  analysis_postgres_data: